### ISSUE TITLE
Comentarios sobre el ejercicio

### ISSUE THREAD

**Issue by m4n50n** [juanmism/4Geeks-My-first-photo-feed#1]
Hola Juanmi,

✔ muy bien trabajado este ejercicio.

☝ **Comentarios / mejoras**:
1. Para conseguir alinear a los extremos el título y el número del post así:
![image](https://user-images.githubusercontent.com/92524023/201518909-dd3035f6-0bbd-4b00-9fdf-8b2225c46fba.png)

Has usado estas dos propiedades:
![image](https://user-images.githubusercontent.com/92524023/201518924-8b4ca0db-2af8-4156-961a-727a6a41aebb.png)

De forma que al sumarse el width y el margin-right fuerzan a que el número se vaya a la izquierda. Esto no es del todo correcto y además podrías ahorrarte establecer width y margin-right fijo simplemente añadiendo `justify-content` a `#headph1` aprovechando que es flex. Es decir:
![image](https://user-images.githubusercontent.com/92524023/201518981-5801706b-3a0d-4c23-b85a-f61290520e02.png)

2. A `#photo1` le has asignado un `height: 500px;`, lo que provoca esto:
![image](https://user-images.githubusercontent.com/92524023/201519036-240a6c93-6ae6-4371-945f-559e1e25412a.png)

Queda mucho espacio debajo debido a que hay poco contenido. 

Y además, si hubiera demasiado contenido pasaría esto:
![image](https://user-images.githubusercontent.com/92524023/201519060-9fc27233-84ee-452b-9524-8bd247687bcb.png)

A lo que voy es que establecer un alto concreto puede llevar a error, así que lo mejor es no ponerlo y que sea el navegador el que interprete el tamaño del post. Obviamente pueden usarse otras formas de restricción, pero al menos en este caso no tendrías errores de visualización.

**Comment by juanmism** [comment]
Corregido. Gracias
